### ISSUE TITLE
Add to PyPI

### ISSUE THREAD

**Issue by szaghi** [rasbt/markdown-toclify#6]
Hi all,

this tool is very useful, but it can become a killer-app if it is included into the PyPi for easy install.

I use Travis CI for building and testing also documentation: presently, I have to clone/get markdown-toclify manually from github before using it for my docs, but it would be very nice to have the possibility to specify it as an automatic dependency of the installer/builder (e.g. pybuilder) that is automatically installed by Travis CI (or similar). 

If you add markdown-toclify to PyPi, it is allowed to install easily with 

```shell
pip install markdown-toclify
```
or even more easy to specify it into setuptools as a requirement. 

I hope you think to this improvement.

Thank you for sharing this great tool.

My best regards.

**Comment by rasbt** [comment]
Thanks for the suggestions. Sure, I can add it to PyPI, why not :). But I probably should add some wrapper function so that it can be used within Python equivalent to the current `argparse` command line options.

**Comment by szaghi** [comment]
I am not sure I understand the concerning about `argparse`. Can you be more explicit? I would like to help, in the remote case I am able to do :-)

**Comment by rasbt** [comment]
Thanks for offering your help. What I had in mind -- before I upload it to PyPI -- was adding a small function so that a user cannot only use it via

`python -m markdown_toclify.py input.md -o output.md --back_to_top`

but also can do the same thing by calling a function within Python:

    from markdown_toclify import markdown_toclify
    markdown_toclify(input='./input.md', output='output.md', back_to_top=True)

It's pretty simple, I can do it later or maybe tomorrow, I just also want to add some more documentation then before I upload it to PyPI.

**Comment by szaghi** [comment]
Ok, thank you. I like learn Python...

**Comment by rasbt** [comment]
Alright, it should be available via pip now :)

**Comment by szaghi** [comment]
Great!
